version: "3"

services:
    tweetpool:
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run start
        ports: 
            - "8080:8080"
        depends_on: 
            - mongo
            - elasticsearch

    mongo:
        image: mongo:latest
        ports: 
            - 27017:27017
        
    mongo_express:
        image: mongo-express:latest
        ports:
            - 8082:8081
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_AUTH_DATABASE=tweets
            - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
        depends_on: 
            - mongo 
        
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
        ports: 
            - 9200:9200
        environment:
            - discovery.type=single-node
         